user muhammad_zeeshan;
events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    
    access_log off;
    error_log stderr;

    server {
        listen 80;
        server_name timelineplus.site www.timelineplus.site localhost;

        root /home/muhammad_zeeshan/Documents/Zeeshan/timeline-earn/dist;
        index index.html;

        # Frontend (Static Files)
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Backend (API) Proxy
        location /api/ {
            proxy_pass http://127.0.0.1:5000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
        
        # Backend (Uploads) Proxy
        location /uploads/ {
            proxy_pass http://127.0.0.1:5000;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }
    }
}
